import Navigation from "../components/navigation"

// layout.tsx는 삭제해도 next에서 감지하고 자동으로 파일 생성함
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

// 모든 페이지들은 아래 구조로 렌더링된다.
// <Layout>
//   <각 page 컴포넌트 />
// </Layout>
// 즉, 레이아웃 컴포넌트 안에 각 url로 인식한 페이지 컴포넌트가 존재한다.

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Navigation />
        {children}
      </body>
    </html>
  )
}
